---
title: "Data Cleaning"
author: "Andrew Edwards, Nick Oakley, and Lauren Pagel"
date: "2024-11-05"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(readxl)
library(dplyr)
```



```{r, echo=FALSE}
# Define relative file paths
path_is_students <- "IS Major Students.xlsx"
path_is_majors <- "IS Major Students - Majors.xlsx"
path_is_grades <- "IS Major Students - Grades.xlsx"
path_is_grades_updated <- "IS Major Students - Grades -updated.xlsx"
path_is_degrees_awarded <- "IS Major Students - Degrees Awarded (1).xlsx"
path_is_credit_hours <- "IS Major Students - Credit Hours.xlsx"
path_is_attributes_gpa <- "IS Major Students - Attributes and GPA.xlsx"

# Read each file into a data frame
df_is_students <- read_excel(path_is_students, col_types = "text")
na_rows <- is.na(df_is_students$`Student ID`)
df_is_students <- df_is_students[!na_rows, ]

# Read another file in
df_is_majors <- read_excel(path_is_majors, col_types = "text")

# Fill missing values
df_is_majors <- df_is_majors |>
  dplyr::group_by(`Major`) |>
  tidyr::fill(`Student ID`, `Cohort Term`, .direction = "down") |>
  dplyr::ungroup()

df_is_grades <- read_excel(path_is_grades, col_types = "text")

df_is_grades_updated <- read_excel(path_is_grades_updated, col_types = "text")


df_is_degrees_awarded <- read_excel(path_is_degrees_awarded, col_types = "text")
df_is_degrees_awarded <- df_is_degrees_awarded |>
  tidyr::fill(`Student ID`, `Term Code`, `Degree Type`, `Degree`, .direction = "down")


df_is_credit_hours <- read_excel(path_is_credit_hours, col_types = "text")
df_is_credit_hours <- df_is_credit_hours |>
  tidyr::fill(`Student ID`)

df_is_attributes_gpa <- read_excel(path_is_attributes_gpa, col_types = "text")
df_is_attributes_gpa <- df_is_attributes_gpa |>
  tidyr::fill('Student ID', 'Gender', 'First Generation Indicator')
```

```{r, echo=FALSE}
# Define relative file paths for BA Major Students
path_ba_attributes_gpa <- "BA Major Students - Attributes and GPA.xlsx"
path_ba_credit_hours <- "BA Major Students - Credit Hours.xlsx"
path_ba_degrees_awarded <- "BA Major Students - Degrees Awarded.xlsx"
path_ba_grades_updated <- "BA Major Students - Grades -updated.xlsx"
path_ba_grades <- "BA Major Students - Grades.xlsx"
path_ba_majors <- "BA Major Students - Majors.xlsx"
path_ba_students <- "BA Major Students.xlsx"

# Read each file into a data frame
df_ba_attributes_gpa <- read_excel(path_ba_attributes_gpa, col_types = "text")
df_ba_attributes_gpa <- df_ba_attributes_gpa |>
  tidyr::fill('Student ID', 'Gender', 'First Generation Indicator')

df_ba_credit_hours <- read_excel(path_ba_credit_hours, col_types = "text")
df_ba_credit_hours <- df_ba_credit_hours |>
  tidyr::fill(`Student ID`)

df_ba_degrees_awarded <- read_excel(path_ba_degrees_awarded, col_types = "text")
df_ba_degrees_awarded <- df_ba_degrees_awarded |>
  tidyr::fill(`Student ID`, `Term Code`, `Degree Type`, `Degree`, .direction = "down")

df_ba_grades_updated <- read_excel(path_ba_grades_updated, col_types = "text")

df_ba_grades <- read_excel(path_ba_grades, col_types = "text")

df_ba_majors <- read_excel(path_ba_majors, col_types = "text")

# Fill missing values
df_ba_majors <- df_ba_majors |>
  dplyr::group_by(`BA Major`) |>
  tidyr::fill(`Student ID`, `Cohort Term`, .direction = "down") |>
  dplyr::ungroup()

df_ba_students <- read_excel(path_ba_students, col_types = "text")

# delete NA rows
na_rows <- is.na(df_ba_students$`Student ID`)
df_ba_students <- df_ba_students[!na_rows, ]

```

```{r, echo = FALSE}
## Cleaning df_is_students
## identify non numeric rows
df_is_students <- df_is_students[!is.na(as.numeric(df_is_students$`Student ID`)), ]

## convert student id and enrolled student count to numeric column type
df_is_students$`Student ID` = as.numeric(df_is_students$`Student ID`)
df_is_students$`Enrolled Student Count` = as.numeric(df_is_students$`Enrolled Student Count`)

# check for na values
na_counts <- sapply(df_is_students, function(x) sum(is.na(x)))

## Cleaning df_is_majors
head(df_is_majors)
na_counts <- sapply(df_is_majors, function(x) sum(is.na(x)))
print(na_counts)

## delete row 2027 onward -- this only provides info on data
df_is_majors <- df_is_majors[1:2026, ]
na_counts <- sapply(df_is_majors, function(x) sum(is.na(x)))
print(na_counts)
```


